dist: trusty
language: erlang
sudo: false
addons:
  postgresql: 9.6
before_install:
- wget https://s3.amazonaws.com/travis-otp-releases/binaries/ubuntu/12.04/x86_64/erlang-${HEXPM_OTP}-nonroot.tar.bz2
- mkdir -p ${HEXPM_OTP_PATH}
- tar -xf erlang-${HEXPM_OTP}-nonroot.tar.bz2 -C ${HEXPM_OTP_PATH} --strip-components=1
- "${HEXPM_OTP_PATH}/Install -minimal $(pwd)/${HEXPM_OTP_PATH}"
- wget http://s3.hex.pm/builds/elixir/${HEXPM_ELIXIR}.zip
- unzip -d ${HEXPM_ELIXIR_PATH} ${HEXPM_ELIXIR}.zip
- wget http://s3.hex.pm/builds/elixir/${ELIXIR}.zip
- unzip -d elixir ${ELIXIR}.zip
- export PATH=$(pwd)/elixir/bin:${PATH}
- mkdir -p ${HEXPM_MIX_HOME}
- PATH=$(pwd)/${HEXPM_ELIXIR_PATH}/bin:$(pwd)/${HEXPM_OTP_PATH}/bin:${PATH} MIX_HOME=$(pwd)/${HEXPM_MIX_HOME}
  MIX_ARCHIVES=$(pwd)/${HEXPM_MIX_HOME} mix local.hex --force
- PATH=$(pwd)/${HEXPM_ELIXIR_PATH}/bin:$(pwd)/${HEXPM_OTP_PATH}/bin:${PATH} MIX_HOME=$(pwd)/${HEXPM_MIX_HOME}
  MIX_ARCHIVES=$(pwd)/${HEXPM_MIX_HOME} mix local.rebar --force
- mix local.hex --force
- mix local.rebar --force
before_script:
- git clone https://github.com/hexpm/hexpm.git hexpm
- cd hexpm; PATH=$(pwd)/../${HEXPM_ELIXIR_PATH}/bin:$(pwd)/../${HEXPM_OTP_PATH}/bin:${PATH}
  MIX_HOME=$(pwd)/../${HEXPM_MIX_HOME} MIX_ARCHIVES=$(pwd)/../${HEXPM_MIX_HOME}
  MIX_ENV=hex ../${HEXPM_ELIXIR_PATH}/bin/mix deps.get; cd ..
- cd hexpm; PATH=$(pwd)/../${HEXPM_ELIXIR_PATH}/bin:$(pwd)/../${HEXPM_OTP_PATH}/bin:${PATH}
  MIX_HOME=$(pwd)/../${HEXPM_MIX_HOME} MIX_ARCHIVES=$(pwd)/../${HEXPM_MIX_HOME}
  MIX_ENV=hex ../${HEXPM_ELIXIR_PATH}/bin/mix compile; cd ..
- mix deps.get
- MIX_ENV=test mix deps.compile
script:
- MIX_ENV=test mix compile
- mix test
env:
  global:
  - HEXPM_OTP=20.0
  - HEXPM_ELIXIR=v1.4.5
  - HEXPM_PATH=hexpm
  - HEXPM_ELIXIR_PATH=hexpm_elixir
  - HEXPM_OTP_PATH=hexpm_otp
  - HEXPM_MIX_HOME=hexpm_mix
  - HEXPM_MIX_ARCHIVES=hexpm_mix
matrix:
  include:
  - otp_release: 20.0
    env: ELIXIR=master
  - otp_release: 20.0
    env: ELIXIR=v1.4.5
  - otp_release: 19.3
    env: ELIXIR=master
  - otp_release: 19.3
    env: ELIXIR=v1.4.5
  - otp_release: 19.3
    env: ELIXIR=v1.3.4
  - otp_release: 19.3
    env: ELIXIR=v1.2.6
  - otp_release: 18.3
    env: ELIXIR=v1.3.4
  - otp_release: 18.3
    env: ELIXIR=v1.2.6
  - otp_release: 18.3
    env: ELIXIR=v1.1.1
  - otp_release: 18.3
    env: ELIXIR=v1.0.5
  - otp_release: 17.5
    env: ELIXIR=v1.1.1
  - otp_release: 17.5
    env: ELIXIR=v1.0.5
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
  slack:
    secure: T5QN9luR7rMH4v88yD944QW3C3Itgd3Bh89oJbxNDweC2dyTqOuvJOgzfcFwBtnaT5j/kHOobd4QL7VHFZ+0UawOxxuy8fl7+A9mn02xVOIpn3Ky0qbpW//oApwKVz2x3X3OhuJASYDNj/w074WrjycIuk2iYkjCpIAnY2dSjo0=
